In [1]:
import numpy as np
import pandas as pd
import time
from dobbel import dobbellogger
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
def remove_nan(df):
    counter = 0
    nan = True
    while nan:
        if not df.loc[counter].isna().any():
            nan = False
        counter += 1
    for i in range(counter - 1):
        df = df.drop(index=i)
    df = df.reset_index(drop=True)
    counter = len(df) - 1
    nan = True
    while nan:
        if not df.loc[counter].isna().any():
            nan = False
        counter -= 1
    maxlen = len(df)
    for i in range(maxlen - 1, counter + 1, -1):
        df = df.drop(index=i)
    df = df.reset_index(drop=True)
    for i in range(len(df)):
        df['timestamp'][i] = df['timestamp'][i] - df['timestamp'][0]
    for i in range(len(df)):
        for column in df.columns:
            if np.isnan(df[column][i]):
                deler = (df['timestamp'][i] - df['timestamp'][i - 1]) / (df['timestamp'][i + 1] - df['timestamp'][i - 1])
                df[column][i] = df[column][i - 1] + deler * (df[column][i + 1] - df[column][i - 1])
    return df

In [16]:
print("Leg de dobbelsteen met nummer ", 1, " boven")
dob = dobbellogger()
dob.log(3, 200, 8, 125)
dob.download()
data = dob.datadf
data = remove_nan(data)

#output accelerometer
x_acc = data['x_acc']
y_acc = data['y_acc']
z_acc = data['z_acc']

# output gyro
x_gyro = data['x_gyro']
y_gyro = data['y_gyro']
z_gyro = data['z_gyro']

#vectorize these outputs
gyro = np.array([x_gyro,y_gyro,z_gyro])
acc = np.array([x_acc,y_acc,z_acc])

# Calculate the  means of accelormeter
x_acc_mean = np.mean(data['x_acc'])
y_acc_mean = np.mean(data['y_acc'])
z_acc_mean = np.mean(data['z_acc'])

# Calculate the  gyro means
x_gyro_mean = np.mean(data['x_gyro'])
y_gyro_mean = np.mean(data['y_gyro'])
z_gyro_mean = np.mean(data['z_gyro'])

# # Normalise the mean
# norm = (x_mean**2 + y_mean**2 + z_mean**2)**0.5
# x_norm_mean = x_mean / norm
# y_norm_mean = y_mean / norm
# z_norm_mean = z_mean / norm

# Create vectors from the accelerometer and gyro means
acc_means = np.array([[x_acc_mean], [y_acc_mean], [z_acc_mean]])
gyro_means = np.array([[x_gyro_mean], [y_gyro_mean], [z_gyro_mean]])

print("1 boven: x_gyro_mean =", x_gyro_mean, " y_gyro_mean = ", y_gyro_mean, " z_gyro_mean = ", z_gyro_mean)
print("1 boven: x_acc_mean =", x_acc_mean, " y_acc_mean = ", y_acc_mean, " z_acc_mean = ", z_acc_mean) 

Leg de dobbelsteen met nummer  1  boven
Logging data for 3s
Done! The data is located in self.datadf
1 boven: x_gyro_mean = -0.16679509968030223  y_gyro_mean =  0.46826604745298067  z_gyro_mean =  0.04395644809578231
1 boven: x_acc_mean = -0.6523708895317414  y_acc_mean =  -0.035981081916601154  z_acc_mean =  -0.8215344570967636


In [20]:
#Define initial values
D_0 = np.identity(3)
b_a = np.array([[0],[0],[0]])
b_omega = gyro_means
cov_acc = np.cov(acc)
cov_gyro = np.cov(gyro)
x_0 = np.array([[1],[0],[0],[0]])
theta = np.array([D_0])
print(b_a)
print(D_0)
print(b_omega)
print(cov_acc)
print(cov_gyro)

[[0]
 [0]
 [0]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-0.1667951 ]
 [ 0.46826605]
 [ 0.04395645]]
[[1.00803168e-05 5.14633119e-06 4.60734536e-07]
 [5.14633119e-06 2.04282113e-05 7.60213406e-07]
 [4.60734536e-07 7.60213406e-07 1.15120514e-05]]
[[ 0.00665623  0.00020042  0.00030583]
 [ 0.00020042  0.00434655 -0.00077061]
 [ 0.00030583 -0.00077061  0.00607711]]


In [14]:
for i in range (500):

[[-0.65234375 -0.64379883 -0.64135742 ... -0.65087891 -0.65063477
  -0.65014648]
 [-0.03417969 -0.0390625  -0.04418945 ... -0.03686523 -0.03857422
  -0.03662109]
 [-0.83618164 -0.82519531 -0.81860352 ... -0.8190918  -0.81665039
  -0.81713867]]
